# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: syoiminserver
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: e-learning
# "service" is the name of this project. This will also be added to your AWS resource names.
service: e-learning

stages:
  default:
    params:
      tableName: "users-table-${sls:stage}"

provider:
  name: aws
  runtime: nodejs20.x
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - Fn::GetAtt: [MainTable, Arn]
  environment:
    USERS_TABLE: ${param:tableName}

functions:
  api:
    handler: handler.handler
    events:
      - http:
          path: /lectures
          method: GET
          cors: true
      - http:
          path: /lectures
          method: POST
          cors: true     
      - http:
          path: /lectures/{lectureId}
          method: GET
          cors: true    

resources:
  Resources:
    MainTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${param:tableName}
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: PK
            AttributeType: S
          - AttributeName: SK
            AttributeType: S
        KeySchema:
          - AttributeName: PK
            KeyType: HASH
          - AttributeName: SK
            KeyType: RANGE